name: test2-tests

on:
  pull_request:
    branches:
      - 'feature/*'
    paths:
      - "test2/**"
  pull_request_target:
    branches:
      - dev-new

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: cat test
        run: |
          cd ./test2/
          cat test.txt